apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fantasy-world
  namespace: default
  labels:
    app:  fantasy-world
spec:
  selector:
    matchLabels:
      app: fantasy-world
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  fantasy-world
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  fantasy-map
        image:  "kinddndmap:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  9000
          name:  fantasy-map
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      - name:  fantasy-towns
        image:  "kinddnd:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8090
          name:  fantasy-towns
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
    