apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  password: imSoSecretYouWouldNeverGuessItAnytimeSoon
  # Example:
  # password: {{ .Values.password | b64enc }}
  # Perhaps you should use
  # https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar?in=vault/kubernetes