apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fantasy-map
  namespace: default
  labels:
    app: fantasy-map
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi