apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cap10bills-fantasy-map
  namespace: default
  labels:
    app: cap10bills-fantasy-map
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi